version: "3.9"

services:
  terraform:
    container_name: nextjs-grpc-infra-app
    image: utkusarioglu/tf-k8s-devcontainer:1.2.15
    volumes:
      - type: bind
        source: ../../../..
        target: /utkusarioglu-com/projects/nextjs-grpc
