version: "3.9"

services:
  terraform:
    container_name: nextjs-grpc-infra-app
    image: utkusarioglu/terraform-kubernetes-devcontainer:1.2.13
    volumes:
      - ../../..:/utkusarioglu-com/projects/nextjs-grpc
